apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tvyt6lymu-go 
  janus-idp.io/tekton: tvyt6lymu-go
  backstage.io/kubernetes-id: tvyt6lymu-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tvyt6lymu-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml